namespace shared;

public enum MessageType
{
    ROBOTDATA,
    TRAINDATA,
    TRAINLINES,
    USEDSTATIONS,
    PACKAGEDATA,
    SIMULATIONSTATE,
    SETTINGS,
    SETSIMULATIONSPEED,
    STARTSIMULATION,
    STOPSIMULATION,
    PAUSESIMULATION,
    CONTINUESTIMULATION
}